version: "3"
services:
  movie:
    image: suryashankar598/phonepaymovieticket:v1
    ports:
      - "8000:80"
    volumes:
      - "movievolume"
    deploy:
      replicas: "5"

  train:
    image: suryashankar598/phonepaytrainticket:v1
    ports:
      - "8001:80"
    volumes:
      - "trainvolume"
    deploy:
      replicas: "5"
      
  
  flight:
    image: suryashankar598/phonepayflightticket:v1
    ports:
      - "8002:80"
    volumes:
      - "flightvolume"
    deploy:
      replicas: "3"
 

  loan:
    image: suryashankar598/phonepayloanpayments:v1
    ports:
      - "8003:80"
    volumes:
      - "loanvolume"
    deploy:
      replicas: "5"
      
